### ISSUE TITLE
Add templates for services

### ISSUE THREAD

**Issue by Akriti3011** [Akriti3011/Electrolocus#4]

**Comment by shahrukhbari99** [comment]
[services.zip](https://github.com/Akriti3011/Electrolocus/files/1443125/services.zip)

**Comment by shahrukhbari99** [comment]
update the css,js folder with new sent along with. It has your files also.

**Comment by Akriti3011** [comment]
Code not working. Don't send such raw templates. Work on it.

**Comment by Akriti3011** [comment]
Services home page template added.
